spring.application.name=User API Service
spring.jpa.properties.hibernate.show_sql=false
server.port=8085

spring.datasource.url=jdbc:mysql://${SPRING_DATASOURCE_HOST}:3306/bhd_users
spring.datasource.username=user_su
spring.datasource.password=my-secret-su-pw
jwt.secret=MnB0j+NfZo5k5CkqzrkYk0AU3JWgdKx7oMZV+hT63vYu3TxXrLv8TL9WjquXZyae+UZBkS8c1B4=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
